### ISSUE TITLE
undefined: dingding.App

### ISSUE THREAD

**Issue by cypggs** [fastwego/dingding-demo#1]
go run ding-dong-bot.go                                                       
# command-line-arguments
./ding-dong-bot.go:19:10: undefined: dingding.App
./ding-dong-bot.go:27:8: undefined: dingding.NewApp
./ding-dong-bot.go:27:24: undefined: dingding.AppConfig

**Comment by Ceelog** [comment]
你这是 master 分支的么？ 看起来是重构之前的版本
